# Generated by Django 5.0.7 on 2024-07-16 20:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=100, unique=True, verbose_name="Почта"
                    ),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="Ф.И.О.")),
                (
                    "comment",
                    models.TextField(
                        blank="True", null="True", verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_letter",
                    models.CharField(max_length=100, verbose_name="Тема письма"),
                ),
                ("body_letter", models.TextField(verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Время начала рассылки",
                    ),
                ),
                (
                    "next_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Время следующей рассылки",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        default=None, verbose_name="Время окончания рассылки"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("once_a_day", "once_a_day"),
                            ("once_a_week", "once_a_week"),
                            ("once_a_month", "once_a_month"),
                        ],
                        default="once_a_day",
                        max_length=100,
                        verbose_name="Периуд",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("start", "start"),
                            ("finish", "finish"),
                            ("created", "created"),
                        ],
                        default="start",
                        max_length=100,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "client",
                    models.ManyToManyField(to="mailing.client", verbose_name="Клиенты"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.CreateModel(
            name="MailingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_mailing_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время последней попытки"
                    ),
                ),
                (
                    "status_mailing",
                    models.CharField(max_length=100, verbose_name="Статус попытки"),
                ),
                (
                    "response_mailing",
                    models.TextField(
                        blank="True", null="True", verbose_name="Ответ сервера"
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        blank="True",
                        null="True",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытка рассылок",
            },
        ),
    ]
